name: CMake with Clang on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true

    - name: Install Clang on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt install -y clang clang-20 cmake ninja-build
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          export VCPKG_ROOT="/home/runner/work/rexglue-sdk-git/rexglue-sdk-git/vcpkg/"
          export CMAKE_TOOLCHAIN_FILE="/home/runner/work/rexglue-sdk-git/rexglue-sdk-git/vcpkg/scripts/buildsystems/vcpkg.cmake"
          ls /home/runner/work/rexglue-sdk-git/rexglue-sdk-git/vcpkg/
    - name: Install LLVM on Windows
      if: matrix.os == 'windows-latest'
      uses: egor-tensin/setup-clang@v1

    - name: Configure CMake
      run: |
          sudo apt update
          sudo apt install -y autoconf autoconf-archive automake libtool
          cmake --preset linux-amd64

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }}
